/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminEstampasRouteImport } from './routes/admin.estampas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEstampasRoute = AdminEstampasRouteImport.update({
  id: '/admin/estampas',
  path: '/admin/estampas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRoute
  '/editor': typeof EditorRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/admin/estampas': typeof AdminEstampasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRoute
  '/editor': typeof EditorRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/admin/estampas': typeof AdminEstampasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designs': typeof DesignsRoute
  '/editor': typeof EditorRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/admin/estampas': typeof AdminEstampasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/designs'
    | '/editor'
    | '/galeria'
    | '/login'
    | '/admin/estampas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/designs' | '/editor' | '/galeria' | '/login' | '/admin/estampas'
  id:
    | '__root__'
    | '/'
    | '/designs'
    | '/editor'
    | '/galeria'
    | '/login'
    | '/admin/estampas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignsRoute: typeof DesignsRoute
  EditorRoute: typeof EditorRoute
  GaleriaRoute: typeof GaleriaRoute
  LoginRoute: typeof LoginRoute
  AdminEstampasRoute: typeof AdminEstampasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/estampas': {
      id: '/admin/estampas'
      path: '/admin/estampas'
      fullPath: '/admin/estampas'
      preLoaderRoute: typeof AdminEstampasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignsRoute: DesignsRoute,
  EditorRoute: EditorRoute,
  GaleriaRoute: GaleriaRoute,
  LoginRoute: LoginRoute,
  AdminEstampasRoute: AdminEstampasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
